language: php
php:
  - 5.3
  - 5.4

script:
  - sudo add-apt-repository -y ppa:chris-lea/node.js
  - sudo apt-get update
  - sudo apt-get -y install nodejs
  - make unit-tests && make javascript-tests
